### ISSUE TITLE
Add/remove liquidity link updates

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#10]
3 Alienbase vaults with ETH:

https://app.beefy.finance/vault/alienbase-cbeth-weth
Add should point to https://app.alienbase.xyz/add/WETH/0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22
Remove should point to https://app.alienbase.xyz/remove/WETH/0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22

https://app.beefy.finance/vault/alienbase-alb-weth
Add should point to https://app.alienbase.xyz/add/WETH/0x1dd2d631c92b1aCdFCDd51A0F7145A50130050C4
Remove should point to https://app.alienbase.xyz/remove/WETH/0x1dd2d631c92b1aCdFCDd51A0F7145A50130050C4

https://app.beefy.finance/vault/alienbase-weth-usdbc
Add should point to https://app.alienbase.xyz/add/0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA/WETH
Remove should point to https://app.alienbase.xyz/remove/0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA/WETH

**Comment by EPETE-EPETE** [comment]
fixed in https://github.com/beefyfinance/beefy-v2/pull/1688
