### ISSUE TITLE
RETH-ETH Aura ETH apy not tally

### ISSUE THREAD

**Issue by CL2727** [beefyfinance/moderator-board#12]
as per title, not sure if there is a need to upgrade the vault

![IMG_3442](https://github.com/beefyfinance/moderator-board/assets/141247090/f6f37e82-2566-4022-bcb7-f223ffef41e4)

![IMG_3443](https://github.com/beefyfinance/moderator-board/assets/141247090/94752bf3-84ca-4fe2-aaad-96550b1fde54)

**Comment by dotpablocom** [comment]
<img width="470" alt="Screenshot 2023-08-28 at 14 23 48" src="https://github.com/beefyfinance/moderator-board/assets/78693916/24ef771a-30fa-4428-96be-467e1255296b"> looks fine now, could be that aura pools require harvest calling and it wasn't
