### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#13]
Missing stablecoin tag: 
https://app.beefy.com/vault/aerodrome-dola-usdbc

Incorrectly labeled as highly correlated: 
https://app.beefy.com/vault/aerodrome-tbtc-weth
https://app.beefy.com/vault/aerodrome-tbtc-usdbc
https://app.beefy.com/vault/aerodrome-weth-usdbc

Should be labeled as blue chip:
https://app.beefy.com/vault/aerodrome-weth-usdbc

**Comment by ReflectiveChimp** [comment]
@erenjaegar77 I think you were going to look at those correlated ones, can you do others at same time please?

**Comment by EPETE-EPETE** [comment]
I have a PR to correct the first two. I don't see any issue with aeordrome-weth-usdbc showing in Blue Chip filter
