### ISSUE TITLE
Incorrect link in ETH-​OP Narrow LP vault 

### ISSUE THREAD

**Issue by GPMS1** [beefyfinance/moderator-board#15]
this is the current link in for "add liquidity"

https://app.gamma.xyz/vault/uni/optimism/details/weth-op-3000-narrow

to my understanding the correct one is this:

https://app.gamma.xyz/vault/uni/op-mainnet/details/weth-op-3000-narrow

**Comment by erenjaegar77** [comment]
Fixed here https://github.com/beefyfinance/beefy-v2/pull/1723
