### ISSUE TITLE
Front end presenting last harvest "3 months ago"

### ISSUE THREAD

**Issue by GPMS1** [beefyfinance/moderator-board#24]
This vault presenting on front UI harvest was 3 months ago, doubt is correct.

https://app.beefy.finance/vault/curve-op-f-wsteth

**Comment by dotpablocom** [comment]
There are no rewards to compound, only trading fees and boost. Last harvest 3 month ago, it's correct.
<img width="1237" alt="Screenshot 2023-10-03 at 18 44 09" src="https://github.com/beefyfinance/moderator-board/assets/78693916/bfe0d4e1-a808-49db-98a1-180ef10b5de6">
<img width="294" alt="Screenshot 2023-10-03 at 18 43 31" src="https://github.com/beefyfinance/moderator-board/assets/78693916/f96aee2a-75b6-46c1-96f2-8ce9ae4414ea">
