### ISSUE TITLE
KLP Pricing issue

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#26]
KLP price mismatch from Kinetix and showing a very high value. Example random wallet on debank vs dashboard:
https://debank.com/profile/0x66c0d9152209b51977047b9dc3b0b5bf2339b67c
https://app.beefy.finance/dashboard/0x66C0d9152209B51977047b9DC3b0B5bf2339b67C

![image](https://github.com/beefyfinance/moderator-board/assets/115495056/4259601e-7727-4ff6-a5c1-3c8837227214)

https://discord.com/channels/755231190134554696/1030498456596398143/1162980642749939813

**Comment by MirthFutures** [comment]
fixed
