### ISSUE TITLE
KLP vault withdrawal fee display

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#27]
Should show 0% withdrawal fee on KLP vault. I don't see any withdrawal fees in recent withdrawals.
https://app.beefy.finance/vault/kinetix-klp

![image](https://github.com/beefyfinance/moderator-board/assets/115495056/6437cec4-8d08-4f97-9729-f300967f3a86)

**Comment by dotpablocom** [comment]
<img width="277" alt="Screenshot 2023-11-06 at 13 52 35" src="https://github.com/beefyfinance/moderator-board/assets/78693916/bcceab40-d93c-4281-8567-fa18229516df">
