### ISSUE TITLE
LP breakdown incorrect for BOB/USDC

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#28]
LP components incorrect
https://app.beefy.finance/vault/quick-gamma-bob-usdc-stable

https://discord.com/channels/755231190134554696/832239396136026163/1170225833848352889
![image](https://github.com/beefyfinance/moderator-board/assets/115495056/0ed2a14f-4948-4ab8-8b6f-e8e799f6b91f)

**Comment by dotpablocom** [comment]
<img width="840" alt="Screenshot 2023-11-06 at 13 53 15" src="https://github.com/beefyfinance/moderator-board/assets/78693916/7bbc7c8f-30a6-4a19-92a1-1291ed801fa8">
