### ISSUE TITLE
BeFTM no rewards over 2 months 

### ISSUE THREAD

**Issue by CL2727** [beefyfinance/moderator-board#33]
User address: 0x73860DC8055a36199fa017e4D9b6584E1497DF85

claim to not earned any ftm from Beftm over the past 2 months.

**Comment by MirthFutures** [comment]
Claimed 153 ftm 8 hours ago? 

https://ftmscan.com/tx/0x0e2e3a69dfdcebc82623538ceb0db9a2679bf730cfb6a215b776a5053993eedf

**Comment by CL2727** [comment]
Sorry, I think he meant to say that after claiming, he didn’t see any additional rewards streaming in. Ie: no ftm claimable after few hours on the UI

**Comment by MirthFutures** [comment]
Refilled the gelato claimer with gas
