### ISSUE TITLE
Yield and PNL missing in CVX/ETH vault

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#35]
https://app.beefy.finance/vault/convex-cvxeth not showing the PNL/Yield info for a deposit for 0x7a5E66249841476f348Bd95C5A8c51025dA28066. Checked other depositors and seems to only be an issue with this address.

![image](https://github.com/beefyfinance/moderator-board/assets/115495056/08438472-4e7f-4615-9333-8de6aaeca454)

Dashboard view: 
![image](https://github.com/beefyfinance/moderator-board/assets/115495056/ca3834bc-8515-4c01-a3c2-2e805aa8632a)

**Comment by dotpablocom** [comment]
https://github.com/beefyfinance/beefy-v2/pull/1903
