### ISSUE TITLE
New stablecoin pairs on base missing stablecoin tag

### ISSUE THREAD

**Issue by armads-beefy** [beefyfinance/moderator-board#5]
https://app.beefy.finance/vault/baseswap-mim-usdbc
https://app.beefy.finance/vault/baseswap-dai-usdbc
https://app.beefy.finance/vault/balancer-base-usdbc-dai
Need stablecoin tag for filter

**Comment by kexleyBeefy** [comment]
https://github.com/beefyfinance/beefy-v2/pull/1645
